### ISSUE TITLE
Update braces to version 2.3.1

### ISSUE THREAD

**Issue by DanielAglbts** [agilebits/emergency-kit#9]
Version of braces prior to 2.3.1 are vulnerable to Regular Expression Denial of Service (ReDoS). Untrusted input may cause catastrophic backtracking while matching regular expressions. This can cause the application to be unresponsive leading to Denial of Service.

**Comment by DanielAglbts** [comment]
This will be fixed once branch [daniel/dependencies](https://github.com/agilebits/emergency-kit/tree/daniel/dependencies) is merged.

**Comment by robyoder** [comment]
Resolved in #12
